### ISSUE TITLE
Drony: update the dnscrypt to the latest version

### ISSUE THREAD

**Issue by cubakcabak** [SuppSandroB/sandrop#130]
latest dnscrypt comes with plugin with some useful features, such as own dns caching and ip6 blocking.

it would be wonderful if drony can integrate latest dnscrypt and gave option in the setting to enable its features, such as own dns caching would be tremendous helpful without relying separately on pdnsd, which in effect not spawning "extra process" on the system.

**Comment by SuppSandroB** [comment]
It would be great if build from offical repo will fit. When I first investigate this it was not working over tcp.
Because Drony users are mostly behind proxy and only tcp or just https is allowed it's crucial that works over tcp. So quite an effort was done to make it work. 
https://github.com/SuppSandroB/dnscrypt-proxy
https://github.com/SuppSandroB/dnscrypt-wrapper
https://github.com/jedisct1/dnscrypt-proxy/issues/374

It's been a while and will need some time to test latest officail build if work okey with tcp. So probably will not be fixed. Maybe if some more users star this issue :)

**Comment by cubakcabak** [comment]
thank you for your explanations.

i never thought that integrating dnscrypt to drony required the dnscrypt source itself to be modified with extra effort.

i wish you could find "easier solutions" when you decide to do that later.

no pressure from me, as i already satisfied with current implementation of dnscrypt in drony.

thank you for your great software, i appreciate much.

_Sent from my EVERCOSS S50D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SuppSandroB** [comment]
closed
